# Generated by Django 5.0 on 2023-12-13 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flip_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_front', models.ImageField(upload_to='')),
                ('title_front', models.CharField(max_length=20)),
                ('title_back', models.CharField(max_length=20)),
                ('description_back', models.TextField()),
                ('link_back', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
