# Generated by Django 5.0 on 2023-12-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("IdPersona", models.IntegerField()),
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                ("correo", models.CharField(max_length=50)),
                ("IdTelefono", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Telefono",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("IdTelefono", models.IntegerField()),
                ("telefono", models.CharField(max_length=15)),
                ("codigoArea", models.CharField(max_length=10)),
            ],
        ),
    ]
