# Generated by Django 5.0 on 2023-12-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddbbdatos", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Telefono",
        ),
        migrations.RemoveField(
            model_name="persona",
            name="IdTelefono",
        ),
        migrations.AddField(
            model_name="persona",
            name="telefono",
            field= models.CharField(max_length=20),
        ),
    ]
