# Generated by Django 5.0 on 2023-12-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddbbdatos", "0002_delete_telefono_remove_persona_idtelefono_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="persona",
            name="telefono",
            field=models.IntegerField(),
        ),
    ]
