# Generated by Django 5.0 on 2023-12-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddbbdatos", "0003_alter_persona_telefono"),
    ]

    operations = [
        migrations.AlterField(
            model_name="persona",
            name="telefono",
            field=models.CharField(max_length=20),
        ),
    ]
